name: NoMoreDroppedItems
version: '${version}'
main: club.aurorapvp.NoMoreDroppedItems
api-version: 1.19
authors: [ Villagers654 ]
description: Gets rid of dropped items without disabling dropping items
website: aurorapvp.club
